version:                "3"
services:
  ppa:
      image:            pymc/pymc
      volumes:
        - .\notebooks:/home/jovyan/work
        - .\data:/home/jovyan/work/data
        - .\out:/home/jovyan/work/out
      ports:
        - 8888:8888
      container_name:   ppa