version:                "3"
services:
  ppa:
      image:            pymc/pymc:4.1.5
      volumes:
        - ./notebooks:/home/jovyan/work
        - ./data:/home/jovyan/work/data
        - ./out:/home/jovyan/work/out
        - ./ppa:/home/jovyan/work/ppa
      ports:
        - 8888:8888
      container_name:   ppa